services:
  hamer-dev:
    build:
      context: ..
      dockerfile: ./docker/hamer-dev.Dockerfile
    container_name: hamer
    working_dir: /app
    tty: true
    stdin_open: true
    shm_size: "16gb"
    volumes:
      - ../:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]